### ISSUE TITLE
Empty slice is not null

### ISSUE THREAD

**Issue by Greast** [kenba/cl3#21]
The pointer from an empty slice is not guaranteed to be null, as such all cl functions where the pointer has to null if the size is 0 can fail, because the api does not ensure that the pointer to empty list is null

**Comment by kenba** [comment]
Thank you for raising this issue Jonas. Please can you provide an example?

**Comment by Greast** [comment]
```RUST
use cl3::device::*;
let id = get_platform_ids().unwrap().pop().unwrap();

use cl3::platform::get_platform_ids;
let devs = &get_device_ids(id, CL_DEVICE_TYPE_DEFAULT) .unwrap()[..1];

use cl3::context::create_context;
use std::ptr::{null, null_mut};
let ctx = create_context(devs, null(), None, null_mut()).unwrap();

use cl3::program::*;
const SRC : &'static str = "__kernel void func(){}";
let program = create_program_with_source(ctx, &[SRC]).unwrap();

use std::ffi::CString;
let no_options = CString::new("").unwrap();
compile_program(program, devs, &no_options, &[], &[], None, null_mut()).unwrap();`
```
In this example, **compile_program** can return Err(-30), which is CL_INVALID_VALUE.
This occurs due to the two empty slices not necessarily pointing to address 0, 
**compile_program** can return CL_INVALID_VALUE if, and I quote "num_input_headers is zero and header_include_names or input_headers are not NULL".

**cl3::program::link_program** also suffers from the same problem

**Comment by kenba** [comment]
I've fixed the empty slice issue in `compile_program` and added an assertion to ensure that the `input_headers` slice and `header_include_names` slice are the same length.

As for `link_program `, it doesn't make sense to call it with an empty `input_programs` slice, so I've added an assertion.

The changes are in the `develop` branch. Please let me know if there are any other issues.

**Comment by Greast** [comment]
I can see **enqueue_nd_range_kernel** suffers from the same problem regarding events

**Comment by kenba** [comment]
Sorry Jonas, but I can't see a problem with `enqueue_nd_range_kernel` events. They are just passed in as number and pointer parameters.

In the [opencl](https://github.com/kenba/opencl3) crate,  the `events` parameter is passed in as a slice, however, that code  checks for an empty list like `compile_program` does now.

Any other issues?

**Comment by kenba** [comment]
Incorporated in version 0.6.5.
