### ISSUE TITLE
Base `cl3` on a fork of `cl-sys` as it is no longer actively maintained.

### ISSUE THREAD

**Issue by kenba** [kenba/cl3#22]
@vmx proposed creating a fork of `cl-sys` (`cl3-sys`?) in issue https://github.com/kenba/opencl3/issues/30 in the `opencl3` repo.  
The rational is that `cl-sys` is no longer actively maintained.

This would involve making a new `ffi` repo, fixing bugs in the `cl-sys` repo, adding new `OpenCL`  features  and attempting to handle features properly between the new repo, this repo and the  `opencl3` repo.

Now would be a good time to do this since Rust is stable at Edition 2021 and the OpenCl SDK is also relatively stable.   
However, I would appreciate Volke's help to design and debug the changes.

**Comment by vmx** [comment]
@kenba sorry for the delay. I'm currently pretty busy and probably will be the next few weeks. Though I still think it would be great to fork `cl3-sys`. As a first step I'd probably wouldn't change much. Probably just fixing the issues that are mentioned on the original repo (like your bug reports there).

**Comment by kenba** [comment]
@vmx no problem, there is no hurry. I just wanted to tie up "loose ends" on these libraries.  

I used `bindgen` and  `cl-sys` to create a repo for a new crate at: [opencl-sys-rs](https://github.com/kenba/opencl-sys-rs) with the intention of using the crate [opencl-sys](https://crates.io/crates/opencl-sys) which doesn't contain anything and hasn't been updated for 4 years! I'm currently waiting for the current owner to respond to my request to add me as an owner...

**Comment by kenba** [comment]
Changes pushed to crates.io.
