### ISSUE TITLE
Make custom clGetDeviceInfo requests easier

### ISSUE THREAD

**Issue by vmx** [kenba/cl3#6]
I need to send a `clGetDeviceInfo` which is not part of the standard, hence not part of the [`DeviceInfo` enum](https://github.com/kenba/cl3/blob/32cf1e27fb1f7149ba09463080b3cda143df3b26/src/device.rs#L171-L296). This means I cannot use the [`get_device_info()`](https://github.com/kenba/cl3/blob/32cf1e27fb1f7149ba09463080b3cda143df3b26/src/device.rs#L339) call.

What I currently do is using the [`api_info_value!()` macro](https://github.com/kenba/cl3/blob/32cf1e27fb1f7149ba09463080b3cda143df3b26/src/macros.rs#L33-L57), it looks like this:

```rust
// Creates a new function called `get_device_info_bus_id` which takes two arguments, the device
// and the parameter ID.
api_info_value!(get_device_info_uint, cl_uint, clGetDeviceInfo);

pub fn get_nvidia_bus_id(d: &opencl3::device::Device) -> Result<u32, ClError> {
    const CL_DEVICE_PCI_BUS_ID_NV: u32 = 0x4008;
    let result = get_device_info_uint(d.id(), CL_DEVICE_PCI_BUS_ID_NV.into())?;
    Ok(result)
}
```

The macros to get values are used inside `get_device_info()` already. As they are useful outside of that function, I wondered if they could be made public. For example moving [`api_info_value!(get_value, cl_uint, clGetDeviceInfo);`](https://github.com/kenba/cl3/blob/32cf1e27fb1f7149ba09463080b3cda143df3b26/src/device.rs#L417) to the top-level of the file and making it public, e.g. as `get_value_cl_uint()`.

This way my code wouldn't need to use a macro and could call it directly.

**Comment by kenba** [comment]
@vmx the reason why the macro "info" functions are hidden inside functions like `get_device_info()` is because they are very hard to use if you don't know what type a given value such as `CL_DEVICE_PCI_BUS_ID_NV` should return, which most users don't.

My preferred solution is for `get_device_info()` to return the correct value for ALL valid values including  `CL_DEVICE_PCI_BUS_ID_NV`.

I'm currently in the process of adding OpenCl extensions to `cl3` , and I plan to add the extension values to  `get_device_info()` in due course. Unfortunately, I couldn't find `CL_DEVICE_PCI_BUS_ID_NV` among them. However, I did find it in a Google search which suggests that it may be a legacy value that Khronos have removed. So I've added it to the list of enumerations that `cl_device_info` supports in the `develop` branch. Please let me know whether it works for you Volker?

Also, please can you let me know where you found the definition of `CL_DEVICE_PCI_BUS_ID_NV` and whether there are any other values that I should add?

**Comment by vmx** [comment]
Thanks Ken for the fast reply. Adding those constants directly would even be better!

The source of truth seems to be https://anteru.net/blog/2014/associating-opencl-device-ids-with-gpus/. The code we use in production (which is using `ocl`) is here: https://github.com/filecoin-project/rust-gpu-tools/blob/54ebc15ddfe0b37762f8d6eb8ddb80a7a3f318e2/src/opencl/utils.rs.

The code I've written based on `cl3` (which passes the tests we have) is:

```rust
#[repr(C)]
#[derive(Debug, Clone, Default)]
struct cl_amd_device_topology {
    r#type: u32,
    unused: [u8; 17],
    bus: u8,
    device: u8,
    function: u8,
}

// Creates a new function called `get_device_info_bus_id` which takes two arguments, the device
// and the parameter ID.
api_info_value!(get_device_info_uint, cl_uint, clGetDeviceInfo);

// NOTE vmx 2021-02-26: This is the same as the `get_string` in `cl3/src/devices.rs`
api_info_vector!(get_device_info_bytes, u8, clGetDeviceInfo);

pub fn get_nvidia_bus_id(d: &opencl3::device::Device) -> Result<u32, ClError> {
    const CL_DEVICE_PCI_BUS_ID_NV: u32 = 0x4008;
    let result = get_device_info_uint(d.id(), CL_DEVICE_PCI_BUS_ID_NV.into())?;
    Ok(result)
}

pub fn get_amd_bus_id(d: &opencl3::device::Device) -> Result<u32, ClError> {
    const CL_DEVICE_TOPOLOGY_AMD: u32 = 0x4037;
    let size = std::mem::size_of::<cl_amd_device_topology>();
    let result = get_device_info_bytes(d.id(), CL_DEVICE_TOPOLOGY_AMD, size)?;
    assert_eq!(result.len(), size);
    let mut topo = cl_amd_device_topology::default();
    unsafe {
        std::slice::from_raw_parts_mut(&mut topo as *mut cl_amd_device_topology as *mut u8, size)
            .copy_from_slice(&result);
    }
    Ok(topo.bus as u32)
}
```

We have some PR open which uses `const CL_DEVICE_PCI_SLOT_ID_NV: u32 = 0x4009;`, which seems to be more unique than `CL_DEVICE_PCI_BUS_ID_NV`. So adding both would be great.

The AMD case is more complicated as it returns a struct. It's OK for me if it just returns the bytes and users would need to do the conversion withing their application.

**Comment by kenba** [comment]
Thanks @vmx, Anteru's blog does indeed seem to be the definitive blog on these *undocumented* `cl_nv_device_attribute_query` extensions! I've added both of them to `device.rs` in the `develop` branch together with the documented `cl_nv_device_attribute_query` extensions from the latest version of `cl_ext.h`.

I'll try to get all the other extensions including the `cl_amd_device_attribute_query` extensions into the library this weekend.

**Comment by kenba** [comment]
@vmx I've now added the `cl_amd_device_attribute_query` values and a function `get_amd_device_topology` to convert a `u8` slice into a `cl_amd_device_topology` structure.

I've tested it on a system with and `AMD` GPU and it seems to work OK using your  `cl_amd_device_topology`  structure.

**Comment by kenba** [comment]
@vmx the changes have now brought over to`opencl3` and published in the latest versions of `cl3` and `opencl3` on `crates.io`.

Your functions `get_nvidia_bus_id` and `get_amd_bus_id` may now be replaced by `opencl3` `Device` methods: `pci_bus_id_nv` and `pci_bus_id_amd` respectively.

**Comment by vmx** [comment]
Thanks a lot for adding the calls I needed. That makes my code indeed simpler.
